# frontend/Dockerfile
FROM node:24-alpine

WORKDIR /app

# Install deps
COPY package*.json ./
RUN yarn

# Copy source code
COPY . .

# Build the app
RUN yarn global add serve
RUN yarn build

# Expose the frontend on port 3000
EXPOSE 3000
CMD ["serve", "dist"]