# kubernetes/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: transcription-service
type: Opaque
data:
  password: dHJhbnNjcmlwdGlvbl9wYXNzd29yZA== # base64 encoded

---
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: transcription-service
type: Opaque
data:
  url: cG9zdGdyZXNxbDovL3RyYW5zY3JpcHRpb25fdXNlcjp0cmFuc2NyaXB0aW9uX3Bhc3N3b3JkQHBvc3RncmVzLXNlcnZpY2U6NTQzMi90cmFuc2NyaXB0aW9uX2Ri # base64 encoded